version: '3.8'

services:
  oauth0:
    image: rhinorus/oauth0:latest
    network_mode: host
    volumes:
      - ./data:/app/db
    restart: unless-stopped
    environment:
      token: ""
      app-port: 8090
    depends_on:
      - postgres

  mylink:
    image: rhinorus/mylink:latest
    network_mode: host
    environment:
      PG_DB: mylink
      PG_USER: postgres
      PG_PASSWORD: postgres
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    network_mode: host
    environment:
      POSTGRES_DB: mylink
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
