spring:
  datasource:
    url:  jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DB:mylink}
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    open-in-view: false
    defer-datasource-initialization: false

spring.application.name: mylink
telegram.token: ${TELEGRAM_BOT_TOKEN}
application.externalUrl: ${EXTERNAL_URL:http://localhost:8080/}
application.centralizedAuthApplicationUrl: ${CENTRALIZED_AUTH_APP_URL:http://localhost:8090}
application.centralizedAuthBotUrl: ${CENTRALIZED_AUTH_BOT_URL:https://t.me/oauth0_bot}

# https reverse proxy support
server:
  forward-headers-strategy: framework