spring:
  datasource:
    url:  jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DB:mylink}
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:fID3P8zg}
  jpa:
    generate-ddl: true
    open-in-view: false
    defer-datasource-initialization: false

spring.application.name: mylink
telegram.token: ${TELEGRAM_BOT_TOKEN}

# https reverse proxy support
server.use-forward-headers: true